// Le frasi di "Gira le Parole", scritte da noi (Penna), per la pagina
// pubblica. Sostituiscono frasi.js, che viene dal sito di partenza: il file
// dichiara lo stesso `const FRASI`, quindi va caricato AL POSTO di
// frasi.js, non insieme (due `const FRASI` nella stessa pagina = errore).
//
// Mazzo rifatto il 05/10/2026 sul modello approvato da Damiano: sul
// tabellone si vede l'INDIZIO, la categoria resta dietro le quinte.
//
// Ogni voce:
//   testo       la frase, con accenti e apostrofi giusti. Solo lettere,
//               spazi e apostrofo: niente cifre, niente punteggiatura,
//               niente virgolette. Entra sempre nel tabellone (RIGHE_TABELLONE).
//   categoria   dietro le quinte: serve al gioco per non far uscire nella
//               stessa partita (round lampo compresi) due frasi della
//               stessa categoria. Sul tabellone compare solo se a una
//               frase manca l'indizio (testoTarga in gioco.js): nel mazzo
//               l'indizio ce l'hanno tutte. 14 categorie,
//               ognuna presente in tutti e quattro i gruppi, ognuna con
//               almeno una frase breve (fino a 22 lettere, LAMPO_MAX_LETTERE)
//               in ogni gruppo.
//   difficolta  "facile" | "media" | "difficile".
//   gruppi      uno o piu` fra "bambini", "famiglia", "tutti", "esperti":
//               bambini  = la risolve da solo un bambino di 7-9 anni;
//               famiglia = tavolo misto, un ragazzo di 9-11 anni la conosce
//                          e un adulto non si annoia;
//               tutti    = cultura generale da adulti, livello televisione;
//               esperti  = le piu` difficili, per chi ci gioca da tempo.
//               I nomi che si leggono sullo schermo li decide il design.
//   indizio     l'ARGOMENTO della frase: il gioco lo mostra nella targa
//               del tabellone, nei round e nel round lampo.
//               Tre forme, mescolate: un soggetto ("Il pesce pagliaccio"),
//               un luogo e un tempo ("Kitty Hawk, dicembre 1903"), un titolo
//               ("Volevo un gatto nero", e la frase dice di cosa parla).
//               Per proverbi e modi di dire l'indizio dice di che cosa
//               parla il detto, e spesso anche che e` un detto.
//               La frase non ripete l'argomento: nessuna parola
//               dell'indizio ne' la sua radice (articoli e preposizioni a
//               parte). Al massimo 40 caratteri, senza punto finale.
//               La frase porta qualcosa di particolare dell'argomento, e
//               si deve poter riconoscere mentre le lettere si scoprono.
const FRASI = [
  // ---- Animali ----
  { testo: "Le uova le porta il papà nella tasca", categoria: "Animali", difficolta: "facile", gruppi: ["bambini"], indizio: "Il cavalluccio marino" },
  { testo: "Il pelo sembra bianco ma la pelle è nera", categoria: "Animali", difficolta: "facile", gruppi: ["bambini"], indizio: "L'orso polare" },
  { testo: "Nasce maschio e può diventare femmina", categoria: "Animali", difficolta: "facile", gruppi: ["bambini"], indizio: "Il pesce pagliaccio" },
  { testo: "Ballano per indicare la strada", categoria: "Animali", difficolta: "media", gruppi: ["bambini", "famiglia"], indizio: "Le api" },
  { testo: "Vola anche all'indietro", categoria: "Animali", difficolta: "media", gruppi: ["bambini", "famiglia"], indizio: "Il colibrì" },
  { testo: "Ha tre cuori e il sangue blu", categoria: "Animali", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"], indizio: "Il polpo" },
  { testo: "Ha sette vertebre nel collo come noi", categoria: "Animali", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "La giraffa" },
  { testo: "Dorme appeso a testa in giù", categoria: "Animali", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "Il pipistrello" },
  { testo: "Il pelo più fitto di tutti", categoria: "Animali", difficolta: "media", gruppi: ["tutti", "esperti"], indizio: "La lontra di mare" },
  { testo: "Resistono nello spazio", categoria: "Animali", difficolta: "difficile", gruppi: ["esperti"], indizio: "I tardigradi" },
  { testo: "Passa quasi tutto il giorno a dormire", categoria: "Animali", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "Il koala" },
  { testo: "Riconoscono la voce dei familiari", categoria: "Animali", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Le elefantesse" },
  { testo: "Si ricorda le cose per mesi", categoria: "Animali", difficolta: "media", gruppi: ["bambini", "famiglia"], indizio: "Il pesce rosso" },
  { testo: "Lo fa arrabbiare il movimento non il colore", categoria: "Animali", difficolta: "media", gruppi: ["tutti", "esperti"], indizio: "Il toro e il drappo rosso" },
  { testo: "Cambia il colore della pelle", categoria: "Animali", difficolta: "facile", gruppi: ["bambini"], indizio: "Il camaleonte" },
  { testo: "La mamma tiene il piccolo nel marsupio", categoria: "Animali", difficolta: "facile", gruppi: ["bambini"], indizio: "Il canguro" },
  { testo: "Cova l'uovo tenendolo sui piedi", categoria: "Animali", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Il pinguino imperatore" },
  { testo: "L'animale più grande mai esistito", categoria: "Animali", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "La balenottera azzurra" },
  { testo: "Nessuno lo batte in una gara di corsa", categoria: "Animali", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "Il ghepardo" },
  { testo: "Depone uova e allatta", categoria: "Animali", difficolta: "difficile", gruppi: ["tutti", "esperti"], indizio: "L'ornitorinco" },
  { testo: "Riposa in piedi su una zampa sola", categoria: "Animali", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "Il fenicottero" },
  { testo: "Un orso che mangia quasi solo bambù", categoria: "Animali", difficolta: "facile", gruppi: ["bambini"], indizio: "Il panda gigante" },
  { testo: "Ha otto zampe e non è un insetto", categoria: "Animali", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "Il ragno" },
  { testo: "Usa il nido degli altri", categoria: "Animali", difficolta: "media", gruppi: ["tutti", "esperti"], indizio: "Il cuculo" },
  { testo: "Il braccio perso ricresce", categoria: "Animali", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "La stella marina" },

  // ---- Musica ----
  { testo: "Prima diceva buongiorno a tutti", categoria: "Musica", difficolta: "facile", gruppi: ["bambini"], indizio: "Happy Birthday" },
  { testo: "Il do si chiamava ut", categoria: "Musica", difficolta: "media", gruppi: ["bambini"], indizio: "Le note musicali" },
  { testo: "Figaro qua Figaro là Figaro su Figaro giù", categoria: "Musica", difficolta: "media", gruppi: ["tutti", "esperti"], indizio: "Il barbiere di Siviglia" },
  { testo: "Nello spartito c'è un cane che abbaia", categoria: "Musica", difficolta: "difficile", gruppi: ["esperti"], indizio: "Le quattro stagioni di Vivaldi" },
  { testo: "La melodia viene da una canzone francese", categoria: "Musica", difficolta: "media", gruppi: ["bambini", "famiglia"], indizio: "Brilla brilla piccola stella" },
  { testo: "Lo inventò un padovano a Firenze", categoria: "Musica", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Il pianoforte" },
  { testo: "Che verso ha non lo sa nessuno", categoria: "Musica", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "Il coccodrillo come fa" },
  { testo: "Alla fine arriva il trattore", categoria: "Musica", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "Il pulcino Pio" },
  { testo: "E invece gliene danno uno bianco", categoria: "Musica", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "Volevo un gatto nero" },
  { testo: "Dormi tu dormi tu din don dan", categoria: "Musica", difficolta: "facile", gruppi: ["bambini"], indizio: "Fra Martino campanaro" },
  { testo: "Chi vive in baracca chi suda il salario", categoria: "Musica", difficolta: "media", gruppi: ["tutti"], indizio: "Ma il cielo è sempre più blu" },
  { testo: "Celentano pensa a lei a mezzanotte", categoria: "Musica", difficolta: "media", gruppi: ["tutti", "esperti"], indizio: "Una carezza in un pugno" },
  { testo: "Dove c'era l'erba ora c'è una città", categoria: "Musica", difficolta: "media", gruppi: ["tutti", "esperti"], indizio: "Il ragazzo della via Gluck" },
  { testo: "Vasco la vuole come quelle dei film", categoria: "Musica", difficolta: "media", gruppi: ["tutti"], indizio: "Vita spericolata" },
  { testo: "Le bionde trecce gli occhi azzurri", categoria: "Musica", difficolta: "media", gruppi: ["tutti"], indizio: "La canzone del sole" },
  { testo: "Nek la cerca ma se n'è andata", categoria: "Musica", difficolta: "media", gruppi: ["tutti"], indizio: "Laura non c'è" },
  { testo: "Si canta salendo sul Vesuvio", categoria: "Musica", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Funiculì funiculà" },
  { testo: "Un valzer di De Gregori per dormire", categoria: "Musica", difficolta: "media", gruppi: ["tutti"], indizio: "Buonanotte fiorellino" },
  { testo: "La cantava Casco d'oro", categoria: "Musica", difficolta: "difficile", gruppi: ["tutti", "esperti"], indizio: "Nessuno mi può giudicare" },
  { testo: "Dal tavolo al legno all'albero al seme", categoria: "Musica", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "Ci vuole un fiore" },
  { testo: "La cantano Timon e Pumbaa", categoria: "Musica", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "Hakuna matata" },
  { testo: "Volare oh oh cantare oh oh oh oh", categoria: "Musica", difficolta: "facile", gruppi: ["famiglia", "tutti"], indizio: "Nel blu dipinto di blu" },
  { testo: "Fratelli d'Italia l'Italia s'è desta", categoria: "Musica", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"], indizio: "L'inno di Mameli" },
  { testo: "Quante bestie ha zio Tobia", categoria: "Musica", difficolta: "facile", gruppi: ["bambini"], indizio: "Nella vecchia fattoria" },
  { testo: "La donna è mobile", categoria: "Musica", difficolta: "media", gruppi: ["tutti", "esperti"], indizio: "Il Rigoletto di Verdi" },
  { testo: "Oggi è l'inno dell'Europa", categoria: "Musica", difficolta: "media", gruppi: ["tutti", "esperti"], indizio: "La nona sinfonia di Beethoven" },

  // ---- A tavola ----
  { testo: "È arrivato in Italia dall'America", categoria: "A tavola", difficolta: "facile", gruppi: ["bambini"], indizio: "Il pomodoro" },
  { testo: "Una volta erano viola e gialle", categoria: "A tavola", difficolta: "facile", gruppi: ["bambini"], indizio: "Le carote" },
  { testo: "Con i suoi semi si comprava un coniglio", categoria: "A tavola", difficolta: "facile", gruppi: ["bambini"], indizio: "Il cacao" },
  { testo: "Per i botanici è una bacca", categoria: "A tavola", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "La banana" },
  { testo: "Più di cinquecento litri di latte", categoria: "A tavola", difficolta: "media", gruppi: ["tutti", "esperti"], indizio: "Una forma di Parmigiano" },
  { testo: "La ricetta sta alla Camera di commercio", categoria: "A tavola", difficolta: "difficile", gruppi: ["esperti"], indizio: "Il ragù alla bolognese" },
  { testo: "Una fetta per ogni parte dell'anno", categoria: "A tavola", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "La pizza quattro stagioni" },
  { testo: "Patate a palline con sugo e mozzarella", categoria: "A tavola", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Gli gnocchi alla sorrentina" },
  { testo: "Il formaggio è pecorino romano", categoria: "A tavola", difficolta: "media", gruppi: ["tutti"], indizio: "La cacio e pepe" },
  { testo: "Ha il filo come un telefono", categoria: "A tavola", difficolta: "media", gruppi: ["tutti"], indizio: "Il supplì" },
  { testo: "Ha il cappello ed è bagnato nel rum", categoria: "A tavola", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Il babà" },
  { testo: "Croccante a strati e fatta a conchiglia", categoria: "A tavola", difficolta: "media", gruppi: ["tutti"], indizio: "La sfogliatella riccia" },
  { testo: "A forma di stella con lo zucchero a velo", categoria: "A tavola", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"], indizio: "Il pandoro" },
  { testo: "Ripiene di carne impanate e fritte", categoria: "A tavola", difficolta: "media", gruppi: ["tutti"], indizio: "Le olive ascolane" },
  { testo: "Ricotta canditi e pasta reale verde", categoria: "A tavola", difficolta: "media", gruppi: ["tutti"], indizio: "La cassata siciliana" },
  { testo: "Il dolce di Pasqua col grano dentro", categoria: "A tavola", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "La pastiera napoletana" },
  { testo: "Grano saraceno e verza", categoria: "A tavola", difficolta: "difficile", gruppi: ["tutti", "esperti"], indizio: "I pizzoccheri" },
  { testo: "Palle di pane raffermo", categoria: "A tavola", difficolta: "difficile", gruppi: ["tutti", "esperti"], indizio: "I canederli" },
  { testo: "Soffi ed esprimi un desiderio", categoria: "A tavola", difficolta: "facile", gruppi: ["bambini"], indizio: "La torta di compleanno" },
  { testo: "Il chicco di mais scoppia col calore", categoria: "A tavola", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "I popcorn" },
  { testo: "Lo fanno le api con il nettare dei fiori", categoria: "A tavola", difficolta: "facile", gruppi: ["bambini"], indizio: "Il miele" },
  { testo: "Ha i semini fuori", categoria: "A tavola", difficolta: "facile", gruppi: ["bambini"], indizio: "La fragola" },
  { testo: "Canditi e uvetta a Natale", categoria: "A tavola", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "Il panettone" },
  { testo: "Savoiardi caffè e mascarpone", categoria: "A tavola", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Il tiramisù" },
  { testo: "Viene dal fiore del croco", categoria: "A tavola", difficolta: "media", gruppi: ["tutti", "esperti"], indizio: "Lo zafferano" },
  { testo: "Il colore del saio dei frati", categoria: "A tavola", difficolta: "media", gruppi: ["tutti"], indizio: "Il cappuccino" },

  // ---- Fiabe e libri ----
  { testo: "La scarpetta all'inizio era un sandalo", categoria: "Fiabe e libri", difficolta: "media", gruppi: ["bambini"], indizio: "Cenerentola" },
  { testo: "La prima volta fu raccontata in barca", categoria: "Fiabe e libri", difficolta: "media", gruppi: ["bambini"], indizio: "Alice nel Paese delle Meraviglie" },
  { testo: "Prende il nome da un'orsa vera", categoria: "Fiabe e libri", difficolta: "media", gruppi: ["bambini"], indizio: "Winnie the Pooh" },
  { testo: "All'inizio Collodi lo faceva morire", categoria: "Fiabe e libri", difficolta: "difficile", gruppi: ["tutti", "esperti"], indizio: "Pinocchio" },
  { testo: "Nonna che orecchie grandi che hai", categoria: "Fiabe e libri", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "Cappuccetto Rosso" },
  { testo: "Trovano una casa fatta di dolci", categoria: "Fiabe e libri", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "Hansel e Gretel" },
  { testo: "Fa diventare marchese il suo padrone", categoria: "Fiabe e libri", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Il gatto con gli stivali" },
  { testo: "Gli uccellini si mangiano le briciole", categoria: "Fiabe e libri", difficolta: "media", gruppi: ["bambini", "famiglia"], indizio: "Pollicino" },
  { testo: "Assaggia la pappa e prova i lettini", categoria: "Fiabe e libri", difficolta: "facile", gruppi: ["bambini"], indizio: "Riccioli d'oro e i tre orsi" },
  { testo: "Suona e i topi lo seguono nel fiume", categoria: "Fiabe e libri", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Il pifferaio di Hamelin" },
  { testo: "Apriti sesamo", categoria: "Fiabe e libri", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"], indizio: "Alì Babà e i quaranta ladroni" },
  { testo: "Al gelo accende una luce dopo l'altra", categoria: "Fiabe e libri", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "La piccola fiammiferaia" },
  { testo: "Ha una gamba sola e ama una ballerina", categoria: "Fiabe e libri", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Il soldatino di stagno" },
  { testo: "Butta giù i capelli per far salire", categoria: "Fiabe e libri", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "Raperonzolo" },
  { testo: "Vince la gara la più lenta", categoria: "Fiabe e libri", difficolta: "facile", gruppi: ["bambini"], indizio: "La lepre e la tartaruga" },
  { testo: "Una canta d'estate e l'altra fa scorte", categoria: "Fiabe e libri", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "La cicala e la formica" },
  { testo: "Una puntura di fuso e cent'anni di sonno", categoria: "Fiabe e libri", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "La bella addormentata nel bosco" },
  { testo: "L'essenziale è invisibile agli occhi", categoria: "Fiabe e libri", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Il piccolo principe" },
  { testo: "Questo matrimonio non s'ha da fare", categoria: "Fiabe e libri", difficolta: "facile", gruppi: ["tutti"], indizio: "I promessi sposi" },
  { testo: "Mi ritrovai per una selva oscura", categoria: "Fiabe e libri", difficolta: "media", gruppi: ["tutti", "esperti"], indizio: "La Divina Commedia" },
  { testo: "Caccia la balena bianca", categoria: "Fiabe e libri", difficolta: "media", gruppi: ["tutti", "esperti"], indizio: "Il capitano Achab" },
  { testo: "Un amico di nome Venerdì", categoria: "Fiabe e libri", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Robinson Crusoe" },

  // ---- Cartoni animati ----
  { testo: "Il primo film fatto tutto al computer", categoria: "Cartoni animati", difficolta: "facile", gruppi: ["bambini"], indizio: "Toy Story" },
  { testo: "Un Oscar grande e sette piccolini", categoria: "Cartoni animati", difficolta: "media", gruppi: ["bambini", "famiglia", "tutti"], indizio: "Biancaneve" },
  { testo: "Esce il primo Topolino", categoria: "Cartoni animati", difficolta: "difficile", gruppi: ["tutti", "esperti"], indizio: "Firenze, dicembre 1932" },
  { testo: "Lo ha inventato un biologo marino", categoria: "Cartoni animati", difficolta: "media", gruppi: ["famiglia", "tutti", "esperti"], indizio: "SpongeBob" },
  { testo: "Dà la voce in cambio di due gambe", categoria: "Cartoni animati", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "La sirenetta" },
  { testo: "Un cucciolo d'uomo cresciuto dai lupi", categoria: "Cartoni animati", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "Il libro della giungla" },
  { testo: "Dory dimentica tutto subito", categoria: "Cartoni animati", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "Alla ricerca di Nemo" },
  { testo: "Ama gli abbracci caldi", categoria: "Cartoni animati", difficolta: "facile", gruppi: ["bambini"], indizio: "Olaf di Frozen" },
  { testo: "Una mamma micia e tre micini a Parigi", categoria: "Cartoni animati", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "Gli Aristogatti" },
  { testo: "Crudelia vuole una pelliccia a pois", categoria: "Cartoni animati", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "La carica dei centouno" },
  { testo: "Il fratellino George ama il dinosauro", categoria: "Cartoni animati", difficolta: "facile", gruppi: ["bambini"], indizio: "Peppa Pig" },
  { testo: "Si tuffa nelle monete come in piscina", categoria: "Cartoni animati", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "Zio Paperone" },
  { testo: "Vive nella palude e odia i visitatori", categoria: "Cartoni animati", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "Shrek" },
  { testo: "Strofini la lampada ed esce il genio", categoria: "Cartoni animati", difficolta: "facile", gruppi: ["bambini"], indizio: "Aladdin" },
  { testo: "Cani pompieri poliziotti e un ragazzo", categoria: "Cartoni animati", difficolta: "facile", gruppi: ["bambini"], indizio: "La Paw Patrol" },
  { testo: "Un'auto rossa da corsa che parla", categoria: "Cartoni animati", difficolta: "facile", gruppi: ["bambini"], indizio: "Saetta McQueen" },
  { testo: "Si rincorrono e vince il più piccolo", categoria: "Cartoni animati", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "Tom e Jerry" },
  { testo: "Chi la tira fuori diventa re", categoria: "Cartoni animati", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "La spada nella roccia" },
  { testo: "Due cani un solo spaghetto e un bacio", categoria: "Cartoni animati", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"], indizio: "Lilli e il vagabondo" },
  { testo: "Gioia e Tristezza nella testa di una bambina", categoria: "Cartoni animati", difficolta: "media", gruppi: ["bambini", "famiglia"], indizio: "Inside Out" },
  { testo: "Non riesce quasi mai a prendere Beep Beep", categoria: "Cartoni animati", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "Willy il Coyote" },
  { testo: "Una famiglia tutta gialla", categoria: "Cartoni animati", difficolta: "facile", gruppi: ["famiglia", "tutti"], indizio: "I Simpson" },

  // ---- Cinema e serie TV ----
  { testo: "Ha una cicatrice a forma di saetta", categoria: "Cinema e serie TV", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"], indizio: "Harry Potter" },
  { testo: "Un hobbit lo deve gettare in un vulcano", categoria: "Cinema e serie TV", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Il signore degli anelli" },
  { testo: "Telefono casa", categoria: "Cinema e serie TV", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"], indizio: "E.T. l'extraterrestre" },
  { testo: "Una DeLorean che viaggia nel tempo", categoria: "Cinema e serie TV", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Ritorno al futuro" },
  { testo: "Kevin resta a casa da solo a Natale", categoria: "Cinema e serie TV", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"], indizio: "Mamma ho perso l'aereo" },
  { testo: "I dinosauri scappano dai recinti", categoria: "Cinema e serie TV", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Jurassic Park" },
  { testo: "Un biglietto d'oro nella tavoletta", categoria: "Cinema e serie TV", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"], indizio: "La fabbrica di cioccolato" },
  { testo: "Una strada di mattoni gialli", categoria: "Cinema e serie TV", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"], indizio: "Il mago di Oz" },
  { testo: "Vola tenendosi all'ombrello", categoria: "Cinema e serie TV", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"], indizio: "Mary Poppins" },
  { testo: "In viaggio con una scultura di legno", categoria: "Cinema e serie TV", difficolta: "media", gruppi: ["tutti"], indizio: "Tre uomini e una gamba" },
  { testo: "Nato su una nave non scende mai a terra", categoria: "Cinema e serie TV", difficolta: "difficile", gruppi: ["tutti", "esperti"], indizio: "La leggenda del pianista sull'oceano" },
  { testo: "Alla fine volano via sulle scope", categoria: "Cinema e serie TV", difficolta: "difficile", gruppi: ["esperti"], indizio: "Miracolo a Milano" },
  { testo: "Domani è un altro giorno", categoria: "Cinema e serie TV", difficolta: "media", gruppi: ["tutti", "esperti"], indizio: "Via col vento" },
  { testo: "Un ragazzo finisce dentro il suo libro", categoria: "Cinema e serie TV", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "La storia infinita" },
  { testo: "Proietti scommette all'ippodromo", categoria: "Cinema e serie TV", difficolta: "difficile", gruppi: ["tutti", "esperti"], indizio: "Febbre da cavallo" },
  { testo: "Il custode vede le statue svegliarsi", categoria: "Cinema e serie TV", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "Una notte al museo" },
  { testo: "Un buco nel muro e finiscono in cucina", categoria: "Cinema e serie TV", difficolta: "difficile", gruppi: ["esperti"], indizio: "I soliti ignoti" },
  { testo: "Si può fare", categoria: "Cinema e serie TV", difficolta: "media", gruppi: ["tutti", "esperti"], indizio: "Frankenstein Junior" },
  { testo: "Montalbano sono", categoria: "Cinema e serie TV", difficolta: "media", gruppi: ["tutti"], indizio: "Il commissario di Vigàta" },
  { testo: "Un prete che indaga in bicicletta", categoria: "Cinema e serie TV", difficolta: "facile", gruppi: ["famiglia", "tutti"], indizio: "Don Matteo" },
  { testo: "Il cuore dell'oceano", categoria: "Cinema e serie TV", difficolta: "media", gruppi: ["tutti", "esperti"], indizio: "La collana di Titanic" },
  { testo: "Com'è umano lei", categoria: "Cinema e serie TV", difficolta: "media", gruppi: ["tutti", "esperti"], indizio: "Fantozzi" },

  // ---- Sport e giochi ----
  { testo: "I primi canestri erano cesti da pesche", categoria: "Sport e giochi", difficolta: "media", gruppi: ["bambini"], indizio: "Il basket" },
  { testo: "Un arbitro li inventò guardando un semaforo", categoria: "Sport e giochi", difficolta: "media", gruppi: ["bambini"], indizio: "I cartellini giallo e rosso" },
  { testo: "È fatta quasi tutta d'argento", categoria: "Sport e giochi", difficolta: "facile", gruppi: ["bambini"], indizio: "La medaglia d'oro" },
  { testo: "Sulla Luna ci ha giocato un astronauta", categoria: "Sport e giochi", difficolta: "media", gruppi: ["bambini", "famiglia"], indizio: "Il golf" },
  { testo: "La maratona parte dal castello di Windsor", categoria: "Sport e giochi", difficolta: "difficile", gruppi: ["tutti", "esperti"], indizio: "Londra, Olimpiadi del 1908" },
  { testo: "Il colore della Gazzetta", categoria: "Sport e giochi", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "La maglia rosa" },
  { testo: "Si chiamava Mintonette", categoria: "Sport e giochi", difficolta: "difficile", gruppi: ["esperti"], indizio: "La pallavolo" },
  { testo: "Un pallone bianco e nero fatto per la tv", categoria: "Sport e giochi", difficolta: "media", gruppi: ["tutti", "esperti"], indizio: "Messico, Mondiali del 1970" },
  { testo: "La storia di Webb Ellis è una leggenda", categoria: "Sport e giochi", difficolta: "difficile", gruppi: ["esperti"], indizio: "Il rugby" },
  { testo: "Nessun anello rappresenta un continente", categoria: "Sport e giochi", difficolta: "media", gruppi: ["tutti", "esperti"], indizio: "I cinque cerchi olimpici" },
  { testo: "Solo tu il pallone e il portiere", categoria: "Sport e giochi", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"], indizio: "Il calcio di rigore" },
  { testo: "Alza la bandierina per il fuorigioco", categoria: "Sport e giochi", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Il guardalinee" },
  { testo: "Sulla neve ma in piano e con fatica", categoria: "Sport e giochi", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Lo sci di fondo" },
  { testo: "La cintura nera è dei più bravi", categoria: "Sport e giochi", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "Il karate" },
  { testo: "Viaggia di mano in mano sempre accesa", categoria: "Sport e giochi", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "La fiaccola olimpica" },
  { testo: "Quattro gomme nuove in pochi secondi", categoria: "Sport e giochi", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Il pit stop in Formula Uno" },
  { testo: "Corri pianti il palo e voli in alto", categoria: "Sport e giochi", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Il salto con l'asta" },
  { testo: "Omini infilati su sbarre che girano", categoria: "Sport e giochi", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "Il calcio balilla" },
  { testo: "Uno conta e gli altri spariscono", categoria: "Sport e giochi", difficolta: "facile", gruppi: ["bambini"], indizio: "Nascondino" },
  { testo: "Il cavallo si muove a elle", categoria: "Sport e giochi", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"], indizio: "Gli scacchi" },
  { testo: "Vince chi trascina la corda dalla sua parte", categoria: "Sport e giochi", difficolta: "facile", gruppi: ["bambini"], indizio: "Il tiro alla fune" },
  { testo: "L'unico che può parare con le mani", categoria: "Sport e giochi", difficolta: "facile", gruppi: ["bambini"], indizio: "Il portiere di calcio" },
  { testo: "Quindici trenta quaranta", categoria: "Sport e giochi", difficolta: "media", gruppi: ["famiglia", "tutti", "esperti"], indizio: "Il punteggio del tennis" },
  { testo: "In piazza del Campo", categoria: "Sport e giochi", difficolta: "media", gruppi: ["tutti", "esperti"], indizio: "Il Palio di Siena" },

  // ---- Luoghi e viaggi ----
  { testo: "Pendeva già mentre la costruivano", categoria: "Luoghi e viaggi", difficolta: "facile", gruppi: ["bambini"], indizio: "La Torre di Pisa" },
  { testo: "Le case stanno su pali di legno", categoria: "Luoghi e viaggi", difficolta: "media", gruppi: ["bambini", "famiglia"], indizio: "Venezia" },
  { testo: "I marinai lo usavano come un faro", categoria: "Luoghi e viaggi", difficolta: "media", gruppi: ["bambini", "famiglia"], indizio: "Lo Stromboli" },
  { testo: "Ha la cresta tutta a denti", categoria: "Luoghi e viaggi", difficolta: "difficile", gruppi: ["esperti"], indizio: "Il Resegone" },
  { testo: "Dallo spazio a occhio nudo non si vede", categoria: "Luoghi e viaggi", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "La Grande Muraglia cinese" },
  { testo: "D'estate col caldo si allunga", categoria: "Luoghi e viaggi", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "La Torre Eiffel" },
  { testo: "Sono le tombe dei faraoni", categoria: "Luoghi e viaggi", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "Le piramidi d'Egitto" },
  { testo: "Prima di diventare verde era color rame", categoria: "Luoghi e viaggi", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "La Statua della Libertà" },
  { testo: "È il nome della campana non della torre", categoria: "Luoghi e viaggi", difficolta: "media", gruppi: ["tutti"], indizio: "Il Big Ben" },
  { testo: "Acqua che cade tra Canada e Stati Uniti", categoria: "Luoghi e viaggi", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Le cascate del Niagara" },
  { testo: "D'estate ci si canta l'opera", categoria: "Luoghi e viaggi", difficolta: "media", gruppi: ["tutti"], indizio: "L'Arena di Verona" },
  { testo: "Il punto più alto delle Alpi", categoria: "Luoghi e viaggi", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Il Monte Bianco" },
  { testo: "La sua guglia sta sui due centesimi", categoria: "Luoghi e viaggi", difficolta: "media", gruppi: ["tutti", "esperti"], indizio: "La Mole Antonelliana" },
  { testo: "Una cupola con un buco e dentro ci piove", categoria: "Luoghi e viaggi", difficolta: "media", gruppi: ["bambini", "famiglia", "tutti"], indizio: "Il Pantheon di Roma" },
  { testo: "Una chiesa ancora in cantiere", categoria: "Luoghi e viaggi", difficolta: "media", gruppi: ["tutti"], indizio: "La Sagrada Familia" },
  { testo: "Marmo bianco costruito per amore", categoria: "Luoghi e viaggi", difficolta: "media", gruppi: ["tutti"], indizio: "Il Taj Mahal" },
  { testo: "Una scorciatoia fra due mari", categoria: "Luoghi e viaggi", difficolta: "difficile", gruppi: ["tutti", "esperti"], indizio: "Il Canale di Suez" },
  { testo: "Fuma sopra Catania", categoria: "Luoghi e viaggi", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "L'Etna" },
  { testo: "Castello sul porto con i torrioni tondi", categoria: "Luoghi e viaggi", difficolta: "difficile", gruppi: ["esperti"], indizio: "Il Maschio Angioino" },
  { testo: "Era sul Toblerone", categoria: "Luoghi e viaggi", difficolta: "media", gruppi: ["tutti", "esperti"], indizio: "Il Cervino" },
  { testo: "La montagna più alta del mondo", categoria: "Luoghi e viaggi", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "L'Everest" },
  { testo: "Un fiume lo ha scavato", categoria: "Luoghi e viaggi", difficolta: "media", gruppi: ["tutti"], indizio: "Il Grand Canyon" },
  { testo: "La città degli Inca sulle Ande", categoria: "Luoghi e viaggi", difficolta: "difficile", gruppi: ["tutti", "esperti"], indizio: "Machu Picchu" },
  { testo: "Ha la forma di una Y rovesciata", categoria: "Luoghi e viaggi", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Il lago di Como" },
  { testo: "La città dei Sassi", categoria: "Luoghi e viaggi", difficolta: "media", gruppi: ["tutti", "esperti"], indizio: "Matera" },
  { testo: "Al tramonto diventano rosa", categoria: "Luoghi e viaggi", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Le Dolomiti" },

  // ---- Personaggi ----
  { testo: "Attraversa il Rubicone", categoria: "Personaggi", difficolta: "facile", gruppi: ["famiglia", "tutti"], indizio: "Giulio Cesare" },
  { testo: "Esiliato all'Elba e poi a Sant'Elena", categoria: "Personaggi", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Napoleone" },
  { testo: "Fa la linguaccia in una foto famosa", categoria: "Personaggi", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Albert Einstein" },
  { testo: "Suonava davanti ai re già da bambino", categoria: "Personaggi", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Mozart" },
  { testo: "Il pittore delle ombre sempre in fuga", categoria: "Personaggi", difficolta: "difficile", gruppi: ["esperti"], indizio: "Caravaggio" },
  { testo: "Il colonnato di San Pietro", categoria: "Personaggi", difficolta: "difficile", gruppi: ["esperti"], indizio: "Gian Lorenzo Bernini" },
  { testo: "Un continente porta il suo nome", categoria: "Personaggi", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Amerigo Vespucci" },
  { testo: "Vede cadere una mela e si chiede perché", categoria: "Personaggi", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Isaac Newton" },
  { testo: "Il primo uomo sulla Luna", categoria: "Personaggi", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"], indizio: "Neil Armstrong" },
  { testo: "Predicava agli uccelli", categoria: "Personaggi", difficolta: "media", gruppi: ["bambini", "famiglia", "tutti"], indizio: "San Francesco d'Assisi" },
  { testo: "Grida eureka e salta fuori dalla vasca", categoria: "Personaggi", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Archimede" },
  { testo: "Un cerchio perfetto a mano libera", categoria: "Personaggi", difficolta: "difficile", gruppi: ["esperti"], indizio: "Giotto" },
  { testo: "La borraccia passata in salita", categoria: "Personaggi", difficolta: "difficile", gruppi: ["tutti", "esperti"], indizio: "Coppi e Bartali" },
  { testo: "Quant'è bella giovinezza", categoria: "Personaggi", difficolta: "difficile", gruppi: ["esperti"], indizio: "Lorenzo il Magnifico" },
  { testo: "Lo chiamavano il prete rosso", categoria: "Personaggi", difficolta: "media", gruppi: ["tutti", "esperti"], indizio: "Antonio Vivaldi" },
  { testo: "Cercava le Indie e trovò l'America", categoria: "Personaggi", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "Cristoforo Colombo" },
  { testo: "Due Nobel in due scienze diverse", categoria: "Personaggi", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Marie Curie" },
  { testo: "Non portò lui la pasta dalla Cina", categoria: "Personaggi", difficolta: "media", gruppi: ["tutti"], indizio: "Marco Polo" },
  { testo: "Favole al telefono e la torta in cielo", categoria: "Personaggi", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Gianni Rodari" },
  { testo: "Vide le lune di Giove col cannocchiale", categoria: "Personaggi", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Galileo Galilei" },
  { testo: "L'eroe dei due mondi", categoria: "Personaggi", difficolta: "facile", gruppi: ["famiglia", "tutti"], indizio: "Giuseppe Garibaldi" },
  { testo: "Era sulle mille lire", categoria: "Personaggi", difficolta: "media", gruppi: ["tutti", "esperti"], indizio: "Maria Montessori" },

  // ---- Scienza e natura ----
  { testo: "Sempre la stessa faccia", categoria: "Scienza e natura", difficolta: "media", gruppi: ["bambini", "famiglia", "tutti"], indizio: "La Luna" },
  { testo: "Ha anelli di ghiaccio e roccia", categoria: "Scienza e natura", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Saturno" },
  { testo: "Gli uccelli sono i loro discendenti", categoria: "Scienza e natura", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "I dinosauri" },
  { testo: "Di giorno all'improvviso si fa buio", categoria: "Scienza e natura", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "L'eclissi di sole" },
  { testo: "Attira il ferro ma non la plastica", categoria: "Scienza e natura", difficolta: "facile", gruppi: ["bambini"], indizio: "La calamita" },
  { testo: "Bolle sotto i cento gradi", categoria: "Scienza e natura", difficolta: "media", gruppi: ["tutti", "esperti"], indizio: "L'acqua in alta montagna" },
  { testo: "Lo producono le piante con la luce", categoria: "Scienza e natura", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "L'ossigeno" },
  { testo: "Portano l'ossigeno in tutto il corpo", categoria: "Scienza e natura", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "I globuli rossi" },
  { testo: "Il lampadario dondola e non c'è vento", categoria: "Scienza e natura", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "Il terremoto" },
  { testo: "Il pianeta color ruggine", categoria: "Scienza e natura", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "Marte" },
  { testo: "Il tempo scorre diverso se vai veloce", categoria: "Scienza e natura", difficolta: "difficile", gruppi: ["tutti", "esperti"], indizio: "La teoria della relatività" },
  { testo: "Africa e Sud America combaciano", categoria: "Scienza e natura", difficolta: "difficile", gruppi: ["tutti", "esperti"], indizio: "La deriva dei continenti" },
  { testo: "I mattoncini di cui sei fatto", categoria: "Scienza e natura", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Le cellule" },
  { testo: "Si mangia persino la luce", categoria: "Scienza e natura", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Il buco nero" },
  { testo: "Indica sempre il nord", categoria: "Scienza e natura", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "La stella polare" },
  { testo: "Cala prima del temporale", categoria: "Scienza e natura", difficolta: "difficile", gruppi: ["tutti", "esperti"], indizio: "La pressione atmosferica" },
  { testo: "Il sole alle spalle e la pioggia davanti", categoria: "Scienza e natura", difficolta: "media", gruppi: ["bambini", "famiglia"], indizio: "L'arcobaleno" },
  { testo: "Prima il lampo e poi il tuono", categoria: "Scienza e natura", difficolta: "facile", gruppi: ["bambini"], indizio: "Il temporale" },
  { testo: "Un neonato ne ha più di un adulto", categoria: "Scienza e natura", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Le ossa" },
  { testo: "Galleggia perché è più leggero dell'acqua", categoria: "Scienza e natura", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "Il ghiaccio" },
  { testo: "La sua luce arriva in otto minuti", categoria: "Scienza e natura", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Il Sole" },
  { testo: "Sassolini che bruciano nel cielo", categoria: "Scienza e natura", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "Le stelle cadenti" },
  { testo: "La nostra galassia", categoria: "Scienza e natura", difficolta: "facile", gruppi: ["famiglia", "tutti"], indizio: "La Via Lattea" },
  { testo: "Più caldo della superficie del Sole", categoria: "Scienza e natura", difficolta: "media", gruppi: ["tutti", "esperti"], indizio: "Il fulmine" },

  // ---- Invenzioni ----
  { testo: "È arancione per farsi trovare", categoria: "Invenzioni", difficolta: "facile", gruppi: ["bambini"], indizio: "La scatola nera" },
  { testo: "Piaggio disse che sembrava un insetto", categoria: "Invenzioni", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "La Vespa" },
  { testo: "I fratelli Wright volano per dodici secondi", categoria: "Invenzioni", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Kitty Hawk, dicembre 1903" },
  { testo: "Esplose per una fuga di gas", categoria: "Invenzioni", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Il primo semaforo" },
  { testo: "Si inaugura l'autostrada dei laghi", categoria: "Invenzioni", difficolta: "difficile", gruppi: ["esperti"], indizio: "Milano, settembre 1924" },
  { testo: "Probabilmente è un falso", categoria: "Invenzioni", difficolta: "difficile", gruppi: ["tutti", "esperti"], indizio: "La bicicletta di Leonardo" },
  { testo: "Marconi la fece arrivare oltre l'oceano", categoria: "Invenzioni", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "La radio" },
  { testo: "Brevettata da Bialetti con De Ponti", categoria: "Invenzioni", difficolta: "media", gruppi: ["tutti"], indizio: "La moka" },
  { testo: "Vuol dire gioca bene", categoria: "Invenzioni", difficolta: "media", gruppi: ["bambini", "famiglia"], indizio: "Il nome LEGO" },
  { testo: "Una colla venuta male", categoria: "Invenzioni", difficolta: "media", gruppi: ["tutti"], indizio: "I Post-it" },
  { testo: "Copiato dai semi che si attaccano al pelo", categoria: "Invenzioni", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Il velcro" },
  { testo: "Una barretta sciolta in tasca a detta di Spencer", categoria: "Invenzioni", difficolta: "media", gruppi: ["tutti"], indizio: "Il forno a microonde" },
  { testo: "Scoperta grazie a una muffa", categoria: "Invenzioni", difficolta: "media", gruppi: ["tutti", "esperti"], indizio: "La penicillina" },
  { testo: "Volano una pecora un'anatra e un gallo", categoria: "Invenzioni", difficolta: "media", gruppi: ["bambini", "famiglia"], indizio: "Versailles, settembre 1783" },
  { testo: "Punti e linee per scrivere da lontano", categoria: "Invenzioni", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Il codice Morse" },
  { testo: "La fila di lettere in alto comincia con QWERTY", categoria: "Invenzioni", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "La tastiera" },
  { testo: "Nati nel Duecento", categoria: "Invenzioni", difficolta: "media", gruppi: ["tutti", "esperti"], indizio: "Gli occhiali" },
  { testo: "Il tessuto blu di Genova", categoria: "Invenzioni", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "I jeans" },

  // ---- Frasi celebri ----
  { testo: "Qui si fa l'Italia o si muore", categoria: "Frasi celebri", difficolta: "difficile", gruppi: ["tutti", "esperti"], indizio: "Calatafimi, maggio 1860" },
  { testo: "Houston abbiamo un problema", categoria: "Frasi celebri", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Apollo 13" },
  { testo: "Elementare Watson", categoria: "Frasi celebri", difficolta: "facile", gruppi: ["famiglia", "tutti"], indizio: "Sherlock Holmes" },
  { testo: "Che la forza sia con te", categoria: "Frasi celebri", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"], indizio: "Star Wars" },
  { testo: "Ai posteri l'ardua sentenza", categoria: "Frasi celebri", difficolta: "difficile", gruppi: ["esperti"], indizio: "Il cinque maggio di Manzoni" },
  { testo: "Sempre caro mi fu quest'ermo colle", categoria: "Frasi celebri", difficolta: "difficile", gruppi: ["tutti", "esperti"], indizio: "L'infinito di Leopardi" },
  { testo: "Siamo uomini o caporali", categoria: "Frasi celebri", difficolta: "difficile", gruppi: ["tutti", "esperti"], indizio: "Totò" },
  { testo: "Verso l'infinito e oltre", categoria: "Frasi celebri", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"], indizio: "Buzz Lightyear" },
  { testo: "Nessuno è perfetto", categoria: "Frasi celebri", difficolta: "media", gruppi: ["tutti", "esperti"], indizio: "A qualcuno piace caldo" },
  { testo: "M'illumino d'immenso", categoria: "Frasi celebri", difficolta: "difficile", gruppi: ["esperti"], indizio: "Mattina di Ungaretti" },
  { testo: "Al mio segnale scatenate l'inferno", categoria: "Frasi celebri", difficolta: "media", gruppi: ["tutti"], indizio: "Il gladiatore" },
  { testo: "Francamente me ne infischio", categoria: "Frasi celebri", difficolta: "difficile", gruppi: ["tutti", "esperti"], indizio: "Rhett Butler" },
  { testo: "C'era una volta", categoria: "Frasi celebri", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "L'inizio delle fiabe" },
  { testo: "Tutti per uno uno per tutti", categoria: "Frasi celebri", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"], indizio: "I tre moschettieri" },

  // ---- Modi di dire ----
  { testo: "Dormire come un ghiro", categoria: "Modi di dire", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"], indizio: "Chi non si sveglia mai" },
  { testo: "Piove a catinelle", categoria: "Modi di dire", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"], indizio: "Fuori diluvia" },
  { testo: "Avere una fame da lupo", categoria: "Modi di dire", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"], indizio: "Lo stomaco vuoto" },
  { testo: "Essere muto come un pesce", categoria: "Modi di dire", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "Si dice di chi tiene un segreto" },
  { testo: "Avere le farfalle nello stomaco", categoria: "Modi di dire", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Modo di dire degli innamorati" },
  { testo: "Prendere lucciole per lanterne", categoria: "Modi di dire", difficolta: "media", gruppi: ["tutti", "esperti"], indizio: "Si dice di chi si sbaglia di grosso" },
  { testo: "Menare il can per l'aia", categoria: "Modi di dire", difficolta: "difficile", gruppi: ["esperti"], indizio: "Chi la tira per le lunghe" },
  { testo: "Costare un occhio della testa", categoria: "Modi di dire", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Un prezzo esagerato" },
  { testo: "Lacrime di coccodrillo", categoria: "Modi di dire", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Un pentimento finto" },
  { testo: "Toccare il cielo con un dito", categoria: "Modi di dire", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "Modo di dire per una gioia enorme" },
  { testo: "Fare il pesce in barile", categoria: "Modi di dire", difficolta: "difficile", gruppi: ["tutti", "esperti"], indizio: "Chi finge di non sapere niente" },
  { testo: "Andare a letto con le galline", categoria: "Modi di dire", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "Chi si corica presto la sera" },
  { testo: "Essere un pesce fuor d'acqua", categoria: "Modi di dire", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Si dice di chi si sente a disagio" },
  { testo: "Avere gli occhi foderati di prosciutto", categoria: "Modi di dire", difficolta: "difficile", gruppi: ["tutti", "esperti"], indizio: "Chi non vede l'evidenza" },
  { testo: "Stonato come una campana", categoria: "Modi di dire", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "Si dice di chi canta male" },
  { testo: "Avere la testa fra le nuvole", categoria: "Modi di dire", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "Modo di dire per i distratti" },

  // ---- Proverbi ----
  { testo: "Rosso di sera bel tempo si spera", categoria: "Proverbi", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"], indizio: "Proverbio sul cielo al tramonto" },
  { testo: "Quando il gatto non c'è i topi ballano", categoria: "Proverbi", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"], indizio: "La classe senza la maestra" },
  { testo: "Le bugie hanno le gambe corte", categoria: "Proverbi", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"], indizio: "Proverbio per chi racconta storie" },
  { testo: "Una ciliegia tira l'altra", categoria: "Proverbi", difficolta: "facile", gruppi: ["bambini", "famiglia"], indizio: "Quando non riesci a smettere" },
  { testo: "Chi va al mulino s'infarina", categoria: "Proverbi", difficolta: "difficile", gruppi: ["tutti", "esperti"], indizio: "Proverbio sulle cattive compagnie" },
  { testo: "Tra i due litiganti il terzo gode", categoria: "Proverbi", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Chi approfitta della lite altrui" },
  { testo: "Chi ha il pane non ha i denti", categoria: "Proverbi", difficolta: "difficile", gruppi: ["tutti", "esperti"], indizio: "Proverbio sulle occasioni sprecate" },
  { testo: "Meglio un uovo oggi che una gallina domani", categoria: "Proverbi", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Il poco ma sicuro" },
  { testo: "Il pesce puzza dalla testa", categoria: "Proverbi", difficolta: "difficile", gruppi: ["tutti", "esperti"], indizio: "Proverbio su chi comanda" },
  { testo: "Aprile ogni goccia un barile", categoria: "Proverbi", difficolta: "difficile", gruppi: ["esperti"], indizio: "Lo dicono i contadini in primavera" },
  { testo: "Chi rompe paga e i cocci sono suoi", categoria: "Proverbi", difficolta: "media", gruppi: ["famiglia", "tutti"], indizio: "Proverbio per chi combina un danno" },
  { testo: "Batti il ferro finché è caldo", categoria: "Proverbi", difficolta: "media", gruppi: ["tutti"], indizio: "Proverbio sul momento giusto" },
];
