// Le frasi di "Gira le Parole", scritte da noi (Penna, 29/09/2026), per la
// pagina pubblica. Sostituiscono frasi.js, che viene dal sito di partenza:
// il file dichiara lo stesso `const FRASI`, quindi va caricato AL POSTO di
// frasi.js, non insieme (due `const FRASI` nella stessa pagina = errore).
//
// Ogni voce:
//   testo       la frase, con accenti e apostrofi giusti. Solo lettere,
//               spazi e apostrofo: niente cifre, niente punteggiatura.
//               Entra sempre nel tabellone 12-14-14-12 (RIGHE_TABELLONE).
//   categoria   il nome sulla targa del tabellone.
//   difficolta  "facile" | "media" | "difficile".
//   gruppi      uno o piu` fra "bambini", "famiglia", "tutti", "esperti":
//               bambini  = la risolve da solo un bambino di 7-9 anni;
//               famiglia = tavolo misto, un ragazzo di 9-11 anni la conosce
//                          e un adulto non si annoia;
//               tutti    = cultura generale da adulti, livello televisione;
//               esperti  = le piu` difficili, per chi ci gioca da tempo.
//               I nomi che si leggono sullo schermo li decide il design.
const FRASI = [
  // ---- Animali ----
  { testo: "Il gatto che fa le fusa", categoria: "Animali", difficolta: "facile", gruppi: ["bambini"] },
  { testo: "Il cane scodinzola quando è contento", categoria: "Animali", difficolta: "facile", gruppi: ["bambini"] },
  { testo: "L'elefante con la proboscide", categoria: "Animali", difficolta: "facile", gruppi: ["bambini"] },
  { testo: "Il canguro con il cucciolo nel marsupio", categoria: "Animali", difficolta: "facile", gruppi: ["bambini", "famiglia"] },
  { testo: "Il pinguino imperatore dell'Antartide", categoria: "Animali", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "La zebra a strisce bianche e nere", categoria: "Animali", difficolta: "facile", gruppi: ["bambini"] },
  { testo: "Il gallo canta all'alba", categoria: "Animali", difficolta: "facile", gruppi: ["bambini", "famiglia"] },
  { testo: "Il ragno tesse la sua tela", categoria: "Animali", difficolta: "facile", gruppi: ["bambini"] },
  { testo: "Il camaleonte cambia colore", categoria: "Animali", difficolta: "media", gruppi: ["bambini", "famiglia"] },
  { testo: "Il pappagallo ripete le parole", categoria: "Animali", difficolta: "facile", gruppi: ["bambini", "famiglia"] },
  { testo: "La balenottera azzurra nell'oceano", categoria: "Animali", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Il bruco diventa farfalla", categoria: "Animali", difficolta: "facile", gruppi: ["bambini", "famiglia"] },
  { testo: "Il fenicottero rosa su una zampa", categoria: "Animali", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Il polpo con otto tentacoli", categoria: "Animali", difficolta: "facile", gruppi: ["bambini", "famiglia"] },
  { testo: "Il panda mangia il bambù", categoria: "Animali", difficolta: "facile", gruppi: ["bambini"] },
  { testo: "Il pipistrello dorme a testa in giù", categoria: "Animali", difficolta: "media", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "Il ghepardo scatta nella savana", categoria: "Animali", difficolta: "media", gruppi: ["bambini", "famiglia"] },
  { testo: "L'ornitorinco depone le uova", categoria: "Animali", difficolta: "difficile", gruppi: ["tutti", "esperti"] },

  // ---- In casa ----
  { testo: "Il telecomando della televisione", categoria: "In casa", difficolta: "facile", gruppi: ["bambini"] },
  { testo: "La lavatrice che centrifuga", categoria: "In casa", difficolta: "facile", gruppi: ["bambini"] },
  { testo: "Lo spazzolino da denti", categoria: "In casa", difficolta: "facile", gruppi: ["bambini"] },
  { testo: "Le pantofole sotto il letto", categoria: "In casa", difficolta: "facile", gruppi: ["bambini"] },
  { testo: "La sveglia che suona al mattino", categoria: "In casa", difficolta: "facile", gruppi: ["bambini"] },
  { testo: "L'asciugamano in bagno", categoria: "In casa", difficolta: "facile", gruppi: ["bambini"] },

  // ---- A scuola ----
  { testo: "La cartella sulle spalle", categoria: "A scuola", difficolta: "facile", gruppi: ["bambini"] },
  { testo: "L'astuccio con i pennarelli", categoria: "A scuola", difficolta: "facile", gruppi: ["bambini"] },
  { testo: "La lavagna e il gessetto", categoria: "A scuola", difficolta: "facile", gruppi: ["bambini"] },
  { testo: "La campanella dell'ultima ora", categoria: "A scuola", difficolta: "facile", gruppi: ["bambini"] },
  { testo: "Ripassare le tabelline", categoria: "A scuola", difficolta: "facile", gruppi: ["bambini"] },
  { testo: "La maestra fa l'appello", categoria: "A scuola", difficolta: "facile", gruppi: ["bambini"] },
  { testo: "Il dettato di italiano", categoria: "A scuola", difficolta: "facile", gruppi: ["bambini"] },
  { testo: "La ricreazione in cortile", categoria: "A scuola", difficolta: "facile", gruppi: ["bambini"] },

  // ---- In cucina ----
  { testo: "La pentola che bolle sul fuoco", categoria: "In cucina", difficolta: "facile", gruppi: ["bambini"] },
  { testo: "Pane burro e marmellata", categoria: "In cucina", difficolta: "facile", gruppi: ["bambini", "famiglia"] },
  { testo: "La torta di compleanno con le candeline", categoria: "In cucina", difficolta: "facile", gruppi: ["bambini", "famiglia"] },
  { testo: "La frittata con le zucchine", categoria: "In cucina", difficolta: "facile", gruppi: ["bambini"] },
  { testo: "Le polpette al sugo", categoria: "In cucina", difficolta: "facile", gruppi: ["bambini", "famiglia"] },
  { testo: "Apparecchiare la tavola", categoria: "In cucina", difficolta: "facile", gruppi: ["bambini", "famiglia"] },
  { testo: "La cioccolata calda con la panna", categoria: "In cucina", difficolta: "facile", gruppi: ["bambini"] },
  { testo: "Il cono gelato al cioccolato", categoria: "In cucina", difficolta: "facile", gruppi: ["bambini"] },

  // ---- Cibo ----
  { testo: "La pizza quattro stagioni", categoria: "Cibo", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "Gli gnocchi alla sorrentina", categoria: "Cibo", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "La pasta cacio e pepe", categoria: "Cibo", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Gli spaghetti alle vongole", categoria: "Cibo", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "I supplì romani", categoria: "Cibo", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "La piadina romagnola", categoria: "Cibo", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Il babà napoletano", categoria: "Cibo", difficolta: "media", gruppi: ["tutti"] },
  { testo: "La sfogliatella napoletana", categoria: "Cibo", difficolta: "media", gruppi: ["tutti"] },
  { testo: "Il pandoro di Verona", categoria: "Cibo", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Le olive ascolane", categoria: "Cibo", difficolta: "media", gruppi: ["tutti"] },
  { testo: "Il risotto ai funghi porcini", categoria: "Cibo", difficolta: "media", gruppi: ["tutti"] },
  { testo: "La cassata siciliana", categoria: "Cibo", difficolta: "media", gruppi: ["tutti"] },
  { testo: "La pastiera napoletana", categoria: "Cibo", difficolta: "media", gruppi: ["tutti"] },
  { testo: "I pizzoccheri della Valtellina", categoria: "Cibo", difficolta: "difficile", gruppi: ["tutti", "esperti"] },
  { testo: "I canederli del Trentino", categoria: "Cibo", difficolta: "difficile", gruppi: ["tutti", "esperti"] },
  { testo: "Il castagnaccio toscano", categoria: "Cibo", difficolta: "difficile", gruppi: ["tutti", "esperti"] },

  // ---- Cartoni animati ----
  { testo: "La sirenetta", categoria: "Cartoni animati", difficolta: "facile", gruppi: ["bambini", "famiglia"] },
  { testo: "Hakuna matata", categoria: "Cartoni animati", difficolta: "media", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "La bella addormentata nel bosco", categoria: "Cartoni animati", difficolta: "facile", gruppi: ["bambini", "famiglia"] },
  { testo: "Biancaneve e i sette nani", categoria: "Cartoni animati", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "Il libro della giungla", categoria: "Cartoni animati", difficolta: "facile", gruppi: ["bambini", "famiglia"] },
  { testo: "Alla ricerca di Nemo", categoria: "Cartoni animati", difficolta: "facile", gruppi: ["bambini", "famiglia"] },
  { testo: "Olaf il pupazzo di neve", categoria: "Cartoni animati", difficolta: "facile", gruppi: ["bambini", "famiglia"] },
  { testo: "Gli Aristogatti", categoria: "Cartoni animati", difficolta: "facile", gruppi: ["bambini", "famiglia"] },
  { testo: "La carica dei centouno", categoria: "Cartoni animati", difficolta: "media", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "George il fratellino di Peppa Pig", categoria: "Cartoni animati", difficolta: "facile", gruppi: ["bambini"] },
  { testo: "Zio Paperone nel suo deposito", categoria: "Cartoni animati", difficolta: "facile", gruppi: ["bambini", "famiglia"] },
  { testo: "Shrek l'orco verde", categoria: "Cartoni animati", difficolta: "facile", gruppi: ["bambini", "famiglia"] },
  { testo: "Il genio della lampada di Aladdin", categoria: "Cartoni animati", difficolta: "facile", gruppi: ["bambini", "famiglia"] },
  { testo: "SpongeBob vive in un ananas", categoria: "Cartoni animati", difficolta: "facile", gruppi: ["bambini"] },
  { testo: "I cuccioli della Paw Patrol", categoria: "Cartoni animati", difficolta: "facile", gruppi: ["bambini"] },
  { testo: "Saetta McQueen di Cars", categoria: "Cartoni animati", difficolta: "facile", gruppi: ["bambini", "famiglia"] },
  { testo: "Tom e Jerry il gatto e il topo", categoria: "Cartoni animati", difficolta: "facile", gruppi: ["bambini", "famiglia"] },
  { testo: "La spada nella roccia", categoria: "Cartoni animati", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Lilli e il vagabondo", categoria: "Cartoni animati", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "Gioia e Tristezza di Inside Out", categoria: "Cartoni animati", difficolta: "media", gruppi: ["bambini", "famiglia"] },

  // ---- Fiabe e favole ----
  { testo: "Cappuccetto Rosso incontra il lupo", categoria: "Fiabe e favole", difficolta: "facile", gruppi: ["bambini", "famiglia"] },
  { testo: "Hansel e Gretel nel bosco", categoria: "Fiabe e favole", difficolta: "facile", gruppi: ["bambini", "famiglia"] },
  { testo: "La scarpetta di cristallo di Cenerentola", categoria: "Fiabe e favole", difficolta: "facile", gruppi: ["bambini", "famiglia"] },
  { testo: "Il gatto con gli stivali", categoria: "Fiabe e favole", difficolta: "facile", gruppi: ["bambini", "famiglia"] },
  { testo: "Le briciole di pane di Pollicino", categoria: "Fiabe e favole", difficolta: "media", gruppi: ["bambini", "famiglia"] },
  { testo: "Riccioli d'oro e i tre orsi", categoria: "Fiabe e favole", difficolta: "facile", gruppi: ["bambini"] },
  { testo: "Il pifferaio di Hamelin", categoria: "Fiabe e favole", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Alì Babà e i quaranta ladroni", categoria: "Fiabe e favole", difficolta: "media", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "La piccola fiammiferaia", categoria: "Fiabe e favole", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Il soldatino di stagno", categoria: "Fiabe e favole", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Raperonzolo nella torre", categoria: "Fiabe e favole", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "La lepre e la tartaruga", categoria: "Fiabe e favole", difficolta: "facile", gruppi: ["bambini", "famiglia"] },
  { testo: "La cicala e la formica", categoria: "Fiabe e favole", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "Il lupo e l'agnello", categoria: "Fiabe e favole", difficolta: "media", gruppi: ["famiglia", "tutti"] },

  // ---- Sport ----
  { testo: "Il calcio di rigore", categoria: "Sport", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "Il guardalinee alza la bandierina", categoria: "Sport", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "La schiacciata a pallavolo", categoria: "Sport", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "Nuotare a stile libero", categoria: "Sport", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "La medaglia di bronzo", categoria: "Sport", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "Il cartellino giallo dell'arbitro", categoria: "Sport", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "Lo sci di fondo", categoria: "Sport", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "La pista di pattinaggio sul ghiaccio", categoria: "Sport", difficolta: "facile", gruppi: ["bambini", "famiglia"] },
  { testo: "Il tuffo dal trampolino", categoria: "Sport", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "Il karate e la cintura nera", categoria: "Sport", difficolta: "facile", gruppi: ["bambini", "famiglia"] },
  { testo: "Il lancio del giavellotto", categoria: "Sport", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "La fiaccola olimpica", categoria: "Sport", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Il cambio gomme ai box", categoria: "Sport", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "La maglia gialla del Tour de France", categoria: "Sport", difficolta: "media", gruppi: ["tutti"] },
  { testo: "Il salto con l'asta", categoria: "Sport", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "La mischia nel rugby", categoria: "Sport", difficolta: "media", gruppi: ["tutti"] },
  { testo: "Il triplice fischio dell'arbitro", categoria: "Sport", difficolta: "media", gruppi: ["tutti"] },

  // ---- Luogo ----
  { testo: "La Torre Eiffel di Parigi", categoria: "Luogo", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "Le piramidi d'Egitto", categoria: "Luogo", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "La Grande Muraglia cinese", categoria: "Luogo", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "La Statua della Libertà a New York", categoria: "Luogo", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "Il Big Ben di Londra", categoria: "Luogo", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "Il deserto del Sahara", categoria: "Luogo", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "La foresta amazzonica", categoria: "Luogo", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Le cascate del Niagara", categoria: "Luogo", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "L'Arena di Verona", categoria: "Luogo", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "La vetta del Monte Bianco", categoria: "Luogo", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "La Mole Antonelliana di Torino", categoria: "Luogo", difficolta: "media", gruppi: ["tutti"] },
  { testo: "Il Pantheon di Roma", categoria: "Luogo", difficolta: "media", gruppi: ["tutti"] },
  { testo: "La Sagrada Familia di Barcellona", categoria: "Luogo", difficolta: "media", gruppi: ["tutti"] },
  { testo: "Il Partenone di Atene", categoria: "Luogo", difficolta: "media", gruppi: ["tutti", "esperti"] },
  { testo: "Il Taj Mahal in India", categoria: "Luogo", difficolta: "media", gruppi: ["tutti"] },
  { testo: "Il Canale di Suez", categoria: "Luogo", difficolta: "difficile", gruppi: ["tutti", "esperti"] },
  { testo: "L'Etna vulcano della Sicilia", categoria: "Luogo", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "La Laguna di Venezia", categoria: "Luogo", difficolta: "facile", gruppi: ["famiglia", "tutti"] },
  { testo: "Il Maschio Angioino di Napoli", categoria: "Luogo", difficolta: "difficile", gruppi: ["esperti"] },
  { testo: "Il Cervino tra Italia e Svizzera", categoria: "Luogo", difficolta: "media", gruppi: ["tutti"] },
  { testo: "L'Everest tetto del mondo", categoria: "Luogo", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Il Grand Canyon in Arizona", categoria: "Luogo", difficolta: "media", gruppi: ["tutti"] },
  { testo: "Machu Picchu in Perù", categoria: "Luogo", difficolta: "difficile", gruppi: ["tutti", "esperti"] },
  { testo: "Lo Stretto di Messina", categoria: "Luogo", difficolta: "media", gruppi: ["tutti"] },
  { testo: "Il Resegone sopra Lecco", categoria: "Luogo", difficolta: "difficile", gruppi: ["esperti"] },

  // ---- Proverbio ----
  { testo: "Chi rompe paga e i cocci sono suoi", categoria: "Proverbio", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Chi tardi arriva male alloggia", categoria: "Proverbio", difficolta: "media", gruppi: ["tutti"] },
  { testo: "Chi si loda s'imbroda", categoria: "Proverbio", difficolta: "media", gruppi: ["tutti", "esperti"] },
  { testo: "Il buongiorno si vede dal mattino", categoria: "Proverbio", difficolta: "facile", gruppi: ["famiglia", "tutti"] },
  { testo: "Rosso di sera bel tempo si spera", categoria: "Proverbio", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "Chi va al mulino s'infarina", categoria: "Proverbio", difficolta: "difficile", gruppi: ["tutti", "esperti"] },
  { testo: "Volere è potere", categoria: "Proverbio", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Batti il ferro finché è caldo", categoria: "Proverbio", difficolta: "media", gruppi: ["tutti"] },
  { testo: "L'occasione fa l'uomo ladro", categoria: "Proverbio", difficolta: "media", gruppi: ["tutti"] },
  { testo: "Chi ha il pane non ha i denti", categoria: "Proverbio", difficolta: "difficile", gruppi: ["tutti", "esperti"] },
  { testo: "Tra i due litiganti il terzo gode", categoria: "Proverbio", difficolta: "media", gruppi: ["tutti"] },
  { testo: "Non c'è rosa senza spine", categoria: "Proverbio", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Il riso abbonda sulla bocca degli stolti", categoria: "Proverbio", difficolta: "difficile", gruppi: ["esperti"] },
  { testo: "Tutti i nodi vengono al pettine", categoria: "Proverbio", difficolta: "media", gruppi: ["tutti"] },
  { testo: "Quando il gatto non c'è i topi ballano", categoria: "Proverbio", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "Chi pecora si fa il lupo se la mangia", categoria: "Proverbio", difficolta: "difficile", gruppi: ["tutti", "esperti"] },
  { testo: "Una ciliegia tira l'altra", categoria: "Proverbio", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "Chi disprezza compra", categoria: "Proverbio", difficolta: "media", gruppi: ["tutti", "esperti"] },
  { testo: "Chi si somiglia si piglia", categoria: "Proverbio", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Meglio un uovo oggi che una gallina domani", categoria: "Proverbio", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Le bugie hanno le gambe corte", categoria: "Proverbio", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "Ogni medaglia ha il suo rovescio", categoria: "Proverbio", difficolta: "media", gruppi: ["tutti"] },
  { testo: "Chi ha fatto trenta può fare trentuno", categoria: "Proverbio", difficolta: "media", gruppi: ["tutti"] },
  { testo: "Il pesce puzza dalla testa", categoria: "Proverbio", difficolta: "difficile", gruppi: ["tutti", "esperti"] },
  { testo: "Acqua passata non macina più", categoria: "Proverbio", difficolta: "media", gruppi: ["tutti"] },
  { testo: "Sotto la neve pane sotto la pioggia fame", categoria: "Proverbio", difficolta: "difficile", gruppi: ["esperti"] },
  { testo: "L'ospite è come il pesce dopo tre giorni puzza", categoria: "Proverbio", difficolta: "media", gruppi: ["tutti"] },
  { testo: "Aprile ogni goccia un barile", categoria: "Proverbio", difficolta: "difficile", gruppi: ["esperti"] },
  { testo: "Tanto tuonò che piovve", categoria: "Proverbio", difficolta: "media", gruppi: ["tutti", "esperti"] },
  { testo: "Chi è causa del suo mal pianga sé stesso", categoria: "Proverbio", difficolta: "difficile", gruppi: ["tutti", "esperti"] },
  { testo: "Fatta la legge trovato l'inganno", categoria: "Proverbio", difficolta: "difficile", gruppi: ["tutti", "esperti"] },
  { testo: "Chi va via perde il posto all'osteria", categoria: "Proverbio", difficolta: "media", gruppi: ["tutti"] },
  { testo: "Il silenzio è d'oro", categoria: "Proverbio", difficolta: "media", gruppi: ["famiglia", "tutti"] },

  // ---- Modo di dire ----
  { testo: "Avere la testa fra le nuvole", categoria: "Modo di dire", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "Piove a catinelle", categoria: "Modo di dire", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "Essere come cane e gatto", categoria: "Modo di dire", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "Avere una fame da lupo", categoria: "Modo di dire", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "Dormire come un ghiro", categoria: "Modo di dire", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "Essere muto come un pesce", categoria: "Modo di dire", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "Avere le farfalle nello stomaco", categoria: "Modo di dire", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Fare il passo più lungo della gamba", categoria: "Modo di dire", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Prendere lucciole per lanterne", categoria: "Modo di dire", difficolta: "media", gruppi: ["tutti", "esperti"] },
  { testo: "Menare il can per l'aia", categoria: "Modo di dire", difficolta: "difficile", gruppi: ["esperti"] },
  { testo: "Avere un diavolo per capello", categoria: "Modo di dire", difficolta: "media", gruppi: ["tutti"] },
  { testo: "Fare castelli in aria", categoria: "Modo di dire", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Costare un occhio della testa", categoria: "Modo di dire", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Salvarsi in calcio d'angolo", categoria: "Modo di dire", difficolta: "media", gruppi: ["tutti"] },
  { testo: "Lacrime di coccodrillo", categoria: "Modo di dire", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Rimanere di sasso", categoria: "Modo di dire", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Toccare il cielo con un dito", categoria: "Modo di dire", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "Fare un buco nell'acqua", categoria: "Modo di dire", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Avere la luna storta", categoria: "Modo di dire", difficolta: "facile", gruppi: ["famiglia", "tutti"] },
  { testo: "Essere il fanalino di coda", categoria: "Modo di dire", difficolta: "media", gruppi: ["tutti"] },
  { testo: "Mettere la pulce nell'orecchio", categoria: "Modo di dire", difficolta: "media", gruppi: ["tutti"] },
  { testo: "Non stare più nella pelle", categoria: "Modo di dire", difficolta: "facile", gruppi: ["famiglia", "tutti"] },
  { testo: "Alzarsi con il piede sbagliato", categoria: "Modo di dire", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "Tenere il piede in due scarpe", categoria: "Modo di dire", difficolta: "media", gruppi: ["tutti"] },
  { testo: "Ridere a crepapelle", categoria: "Modo di dire", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "Essere un pesce fuor d'acqua", categoria: "Modo di dire", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Fare il pesce in barile", categoria: "Modo di dire", difficolta: "difficile", gruppi: ["tutti", "esperti"] },
  { testo: "Andare a letto con le galline", categoria: "Modo di dire", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "Promettere mari e monti", categoria: "Modo di dire", difficolta: "media", gruppi: ["tutti"] },
  { testo: "Scoprire l'acqua calda", categoria: "Modo di dire", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Essere sulla stessa barca", categoria: "Modo di dire", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Avere gli occhi foderati di prosciutto", categoria: "Modo di dire", difficolta: "difficile", gruppi: ["tutti", "esperti"] },

  // ---- Titolo di film ----
  { testo: "Harry Potter e la pietra filosofale", categoria: "Titolo di film", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Il signore degli anelli", categoria: "Titolo di film", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Guerre stellari", categoria: "Titolo di film", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Ritorno al futuro", categoria: "Titolo di film", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Mamma ho perso l'aereo", categoria: "Titolo di film", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "Jurassic Park", categoria: "Titolo di film", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "La fabbrica di cioccolato", categoria: "Titolo di film", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "Il mago di Oz", categoria: "Titolo di film", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "Mary Poppins", categoria: "Titolo di film", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "Indiana Jones e l'ultima crociata", categoria: "Titolo di film", difficolta: "media", gruppi: ["tutti"] },
  { testo: "Tre uomini e una gamba", categoria: "Titolo di film", difficolta: "media", gruppi: ["tutti"] },
  { testo: "Chiedimi se sono felice", categoria: "Titolo di film", difficolta: "media", gruppi: ["tutti"] },
  { testo: "Pane amore e fantasia", categoria: "Titolo di film", difficolta: "difficile", gruppi: ["esperti"] },
  { testo: "La leggenda del pianista sull'oceano", categoria: "Titolo di film", difficolta: "difficile", gruppi: ["tutti", "esperti"] },
  { testo: "Il ragazzo invisibile", categoria: "Titolo di film", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Miracolo a Milano", categoria: "Titolo di film", difficolta: "difficile", gruppi: ["esperti"] },
  { testo: "Via col vento", categoria: "Titolo di film", difficolta: "media", gruppi: ["tutti"] },
  { testo: "La storia infinita", categoria: "Titolo di film", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Febbre da cavallo", categoria: "Titolo di film", difficolta: "difficile", gruppi: ["tutti", "esperti"] },
  { testo: "Una notte al museo", categoria: "Titolo di film", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "Divorzio all'italiana", categoria: "Titolo di film", difficolta: "difficile", gruppi: ["esperti"] },
  { testo: "I soliti ignoti", categoria: "Titolo di film", difficolta: "difficile", gruppi: ["esperti"] },
  { testo: "Frankenstein Junior", categoria: "Titolo di film", difficolta: "media", gruppi: ["tutti"] },

  // ---- Canzone ----
  { testo: "Il coccodrillo come fa", categoria: "Canzone", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "Il pulcino Pio", categoria: "Canzone", difficolta: "facile", gruppi: ["bambini", "famiglia"] },
  { testo: "Volevo un gatto nero", categoria: "Canzone", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "Fra Martino campanaro", categoria: "Canzone", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "Ma il cielo è sempre più blu", categoria: "Canzone", difficolta: "media", gruppi: ["tutti"] },
  { testo: "Una carezza in un pugno", categoria: "Canzone", difficolta: "media", gruppi: ["tutti", "esperti"] },
  { testo: "Il ragazzo della via Gluck", categoria: "Canzone", difficolta: "media", gruppi: ["tutti", "esperti"] },
  { testo: "Vita spericolata", categoria: "Canzone", difficolta: "media", gruppi: ["tutti"] },
  { testo: "La canzone del sole", categoria: "Canzone", difficolta: "media", gruppi: ["tutti"] },
  { testo: "Laura non c'è", categoria: "Canzone", difficolta: "media", gruppi: ["tutti"] },
  { testo: "Funiculì funiculà", categoria: "Canzone", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Parlami d'amore Mariù", categoria: "Canzone", difficolta: "difficile", gruppi: ["esperti"] },
  { testo: "Buonanotte fiorellino", categoria: "Canzone", difficolta: "media", gruppi: ["tutti"] },
  { testo: "Nessuno mi può giudicare", categoria: "Canzone", difficolta: "difficile", gruppi: ["tutti", "esperti"] },
  { testo: "Tintarella di luna", categoria: "Canzone", difficolta: "difficile", gruppi: ["tutti", "esperti"] },
  { testo: "Il gatto e la volpe", categoria: "Canzone", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Ci vuole un fiore", categoria: "Canzone", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "Il valzer del moscerino", categoria: "Canzone", difficolta: "media", gruppi: ["bambini", "famiglia"] },
  { testo: "Siamo solo noi", categoria: "Canzone", difficolta: "media", gruppi: ["tutti"] },

  // ---- Personaggio famoso ----
  { testo: "Giulio Cesare", categoria: "Personaggio famoso", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Napoleone Bonaparte", categoria: "Personaggio famoso", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Cleopatra regina d'Egitto", categoria: "Personaggio famoso", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Albert Einstein", categoria: "Personaggio famoso", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Wolfgang Amadeus Mozart", categoria: "Personaggio famoso", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Giacomo Leopardi", categoria: "Personaggio famoso", difficolta: "media", gruppi: ["tutti"] },
  { testo: "Giovanni Verga e i Malavoglia", categoria: "Personaggio famoso", difficolta: "difficile", gruppi: ["esperti"] },
  { testo: "Michelangelo Merisi da Caravaggio", categoria: "Personaggio famoso", difficolta: "difficile", gruppi: ["esperti"] },
  { testo: "Gian Lorenzo Bernini", categoria: "Personaggio famoso", difficolta: "difficile", gruppi: ["esperti"] },
  { testo: "Enrico Fermi", categoria: "Personaggio famoso", difficolta: "difficile", gruppi: ["tutti", "esperti"] },
  { testo: "Amerigo Vespucci", categoria: "Personaggio famoso", difficolta: "media", gruppi: ["tutti"] },
  { testo: "Camillo Benso conte di Cavour", categoria: "Personaggio famoso", difficolta: "difficile", gruppi: ["esperti"] },
  { testo: "Carlo Collodi", categoria: "Personaggio famoso", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Gianni Rodari", categoria: "Personaggio famoso", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Totò il principe della risata", categoria: "Personaggio famoso", difficolta: "media", gruppi: ["tutti"] },
  { testo: "Isaac Newton", categoria: "Personaggio famoso", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Neil Armstrong sulla Luna", categoria: "Personaggio famoso", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "San Francesco d'Assisi", categoria: "Personaggio famoso", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Archimede di Siracusa", categoria: "Personaggio famoso", difficolta: "media", gruppi: ["tutti", "esperti"] },
  { testo: "Giotto di Bondone", categoria: "Personaggio famoso", difficolta: "difficile", gruppi: ["esperti"] },
  { testo: "Margherita Hack", categoria: "Personaggio famoso", difficolta: "media", gruppi: ["tutti"] },
  { testo: "Fausto Coppi e Gino Bartali", categoria: "Personaggio famoso", difficolta: "media", gruppi: ["tutti", "esperti"] },
  { testo: "Tutankhamon il faraone bambino", categoria: "Personaggio famoso", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Lorenzo il Magnifico", categoria: "Personaggio famoso", difficolta: "media", gruppi: ["tutti", "esperti"] },

  // ---- Scienza e natura ----
  { testo: "Il cuore batte nel petto", categoria: "Scienza e natura", difficolta: "facile", gruppi: ["bambini", "famiglia"] },
  { testo: "La Luna gira intorno alla Terra", categoria: "Scienza e natura", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "Gli anelli di Saturno", categoria: "Scienza e natura", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "I dinosauri si sono estinti", categoria: "Scienza e natura", difficolta: "media", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "L'eclissi di sole", categoria: "Scienza e natura", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "La calamita attira il ferro", categoria: "Scienza e natura", difficolta: "facile", gruppi: ["bambini", "famiglia"] },
  { testo: "L'acqua bolle a cento gradi", categoria: "Scienza e natura", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "La lava che esce dal vulcano", categoria: "Scienza e natura", difficolta: "facile", gruppi: ["bambini", "famiglia"] },
  { testo: "L'ossigeno che respiriamo", categoria: "Scienza e natura", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "I globuli rossi del sangue", categoria: "Scienza e natura", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "La cometa con la coda", categoria: "Scienza e natura", difficolta: "facile", gruppi: ["bambini", "famiglia"] },
  { testo: "L'astronauta nello spazio", categoria: "Scienza e natura", difficolta: "facile", gruppi: ["bambini", "famiglia"] },
  { testo: "Il termometro misura la febbre", categoria: "Scienza e natura", difficolta: "facile", gruppi: ["bambini"] },
  { testo: "Le scosse di terremoto", categoria: "Scienza e natura", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Marte il pianeta rosso", categoria: "Scienza e natura", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "La teoria della relatività", categoria: "Scienza e natura", difficolta: "difficile", gruppi: ["tutti", "esperti"] },
  { testo: "La deriva dei continenti", categoria: "Scienza e natura", difficolta: "difficile", gruppi: ["tutti", "esperti"] },
  { testo: "Il principio di Archimede", categoria: "Scienza e natura", difficolta: "difficile", gruppi: ["tutti", "esperti"] },
  { testo: "Le cellule del corpo umano", categoria: "Scienza e natura", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "La divisione cellulare", categoria: "Scienza e natura", difficolta: "difficile", gruppi: ["esperti"] },
  { testo: "Un buco nero nello spazio", categoria: "Scienza e natura", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "La stella polare indica il nord", categoria: "Scienza e natura", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "La pressione atmosferica", categoria: "Scienza e natura", difficolta: "difficile", gruppi: ["tutti", "esperti"] },

  // ---- Frase celebre ----
  { testo: "Qui si fa l'Italia o si muore", categoria: "Frase celebre", difficolta: "difficile", gruppi: ["tutti", "esperti"] },
  { testo: "Houston abbiamo un problema", categoria: "Frase celebre", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Un piccolo passo per un uomo", categoria: "Frase celebre", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Elementare Watson", categoria: "Frase celebre", difficolta: "media", gruppi: ["famiglia", "tutti"] },
  { testo: "Che la forza sia con te", categoria: "Frase celebre", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "Ai posteri l'ardua sentenza", categoria: "Frase celebre", difficolta: "difficile", gruppi: ["esperti"] },
  { testo: "Sempre caro mi fu quest'ermo colle", categoria: "Frase celebre", difficolta: "difficile", gruppi: ["esperti"] },
  { testo: "Siamo uomini o caporali", categoria: "Frase celebre", difficolta: "difficile", gruppi: ["tutti", "esperti"] },
  { testo: "Verso l'infinito e oltre", categoria: "Frase celebre", difficolta: "facile", gruppi: ["bambini", "famiglia", "tutti"] },
  { testo: "Nessuno è perfetto", categoria: "Frase celebre", difficolta: "media", gruppi: ["tutti"] },
  { testo: "M'illumino d'immenso", categoria: "Frase celebre", difficolta: "difficile", gruppi: ["esperti"] },
  { testo: "Libertà va cercando ch'è sì cara", categoria: "Frase celebre", difficolta: "difficile", gruppi: ["esperti"] },
  { testo: "Al mio segnale scatenate l'inferno", categoria: "Frase celebre", difficolta: "media", gruppi: ["tutti"] },
  { testo: "Francamente me ne infischio", categoria: "Frase celebre", difficolta: "media", gruppi: ["tutti", "esperti"] },
];
